stages:
  - build
  - test
  - deploy

build-job:     
  stage: build
  image: node:alpine
  script:
    - echo "Compiling the code..."
    - npm build
    - echo "Compile complete."

unit-test-job:  
  stage: test 
  script:
      - echo "No Tests Found! Skipping job..."
    # - echo "Running unit tests... This will take about 60 seconds."
    # - yarn test
    # - echo "Code coverage is 90%"

lint-test-job: 
  stage: test
  script:
      - echo "No Tests Found! Skipping lint job..."
    # - echo "Linting code... This will take about 10 seconds."
    # - sleep 10
    # - echo "No lint issues found."

deploy-job:     
  stage: deploy 
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Need to build image artifact"
    - echo "Application successfully deployed."
