apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: astro-app
  template:
    metadata:
      labels:
        app: astro-app
    spec:
      containers:
        - name: astro-app
          image: registry.gitlab.com/robinsond-home-lab/codewitheternal
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: astro-app
spec:
  type: NodePort
  selector:
    app: astro-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000